// This file is auto-generated by the database migration tool
// Do not modify this file manually

export type UserRole = 'USER' | 'ADMIN' | 'CLUB_ADMIN';
export type RequestStatus = 'PENDING' | 'APPROVED' | 'REJECTED' | 'SCHEDULED';

export interface Club {
  id: string;
  slug: string;
  name: string;
  description: string;
  shortDescription?: string;
  cityId: string;
  neighborhood: string;
  addressDisplay: string;
  address?: string;
  coordinates: any;
  contactEmail: string;
  phoneNumber?: string;
  website?: string;
  socialMedia?: any;
  isVerified: boolean;
  isActive: boolean;
  allowsPreRegistration: boolean;
  openingHours: any;
  amenities: string[];
  vibeTags: string[];
  priceRange: string;
  capacity: number;
  foundedYear: number;
  images: string[];
  logoUrl?: string;
  coverImageUrl?: string;
  metaTitle?: string;
  metaDescription?: string;
  createdAt: Date;
  updatedAt: Date;
  rating?: number;
  reviewCount?: number;
}

export interface Profile {
  id: string;
  authId: string;
  email: string;
  role: UserRole;
  tier: string;
  encryptedData?: string;
  avatarUrl?: string;
  bio?: string;
  displayName?: string;
  preferences?: any;
  stats: any;
  isVerified: boolean;
  hasCompletedOnboarding: boolean;
  lastActiveAt?: Date;
  createdAt: Date;
  updatedAt: Date;
  managedClubId?: string;
}

export interface City {
  id: string;
  name: string;
  slug: string;
  country: string;
  region?: string;
  description?: string;
  metaTitle?: string;
  metaDescription?: string;
  latitude?: number;
  longitude?: number;
  timezone: string;
  createdAt: Date;
  updatedAt: Date;
  countryCode: string;
}

export interface Article {
  id: string;
  title: string;
  slug: string;
  excerpt: string;
  content: string;
  category: string;
  tags: string[];
  heroImage?: string;
  heroImageAlt?: string;
  authorName: string;
  authorBio?: string;
  authorAvatar?: string;
  cityId?: string;
  clubId?: string;
  isPublished: boolean;
  publishedAt?: Date;
  featuredOrder: number;
  readTime: number;
  metaTitle?: string;
  metaDescription?: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface MembershipRequest {
  id: string;
  status: RequestStatus;
  message?: string;
  appointmentDate?: Date;
  appointmentNotes?: string;
  encryptedSnapshot?: any;
  userId: string;
  clubId: string;
  reviewedBy?: string;
  reviewedAt?: Date;
  rejectionReason?: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface Review {
  id: string;
  rating: number;
  content?: string;
  userId: string;
  clubId: string;
  isPublic: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface Favorite {
  id: string;
  userId: string;
  clubId: string;
  createdAt: Date;
}

export interface Event {
  id: string;
  slug: string;
  name: string;
  description: string;
  startDate: Date;
  endDate: Date;
  location: string;
  clubId?: string;
  cityId?: string;
  isPublished: boolean;
  imageUrl?: string;
  eventUrl?: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface Notification {
  id: string;
  userId: string;
  type: string;
  title: string;
  message: string;
  isRead: boolean;
  data?: any;
  createdAt: Date;
}

export interface FilterOptions {
  neighborhood: string;
  amenities: string[];
  vibes: string[];
  isVerified: boolean;
  priceRange: string[];
  rating: number;
}